[build]
  command = "yarn build"
  publish = "_site"

[[redirects]]
  from = "/blog"
  to = "/notes"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "/notes/:splat"
  status = 301
  force = true